# Generated by Django 5.1.3 on 2024-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='total_late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
